### ISSUE TITLE
Bug: Send objects example doesn't work

### ISSUE THREAD

**Issue by ChrisChinchilla** [ipfs/docs#139] opened 2018-12-04 19:29 UTC
This of course could just be me, and it's hard to debug, but in `usage.md`

```sh
> hash=`echo "I <3 IPFS -$(whoami)" | ipfs add -q`
> curl "https://ipfs.io/ipfs/$hash"
I <3 IPFS -<your username>
```

Didn't result in the expected output. The `hash` worked, but curl and browser access doesn't return anything, i.e. eventually times out.

**Comment by ChrisChinchilla** [comment] 2018-12-04 19:32
I see the comment below this about potential speed issues, but I've had it running for some time now. Maybe there's a better example so people don't lose interest?

**Comment by Mr0grog** [comment] 2018-12-05 02:59
Well, it’s certainly a problem if this never worked, even after quite a while with your node being online. It might indicate a problem with some router in-between you and ipfs.io not having port 4001 open (which is a different thing we should describe somewhere).

Did the second part about using your local gateway (`curl "http://127.0.0.1:8080/ipfs/$hash"`) work? 

Side note: maybe we should flip the order of those (suggest trying your local gateway before trying a remote one) so that it’ll be more clear where the problem is (in your own local setup or something about your networking) if someone runs into this situation.

**Comment by Mr0grog** [comment] 2018-12-05 03:01
That said, you should probably hit up https://discuss.ipfs.io to troubleshoot that. Then we’d love any changes to the docs that make sense based on what you learn while troubleshooting.

**Comment by jessicaschilling** [comment] 2019-07-26 18:37
@ChrisChinchilla -- just checking in on this one before I close it, since it's been dormant for a while. Thank you!

**Comment by ChrisChinchilla** [comment] 2019-07-29 08:54
@jessicaschilling Checking on what? I did this as part of a hackathon and I'm not sure why it's sat here so long. Might just be worth checking over and seeing if it's still the case.

**Comment by Stebalien** [comment] 2019-07-29 23:45
This is https://github.com/ipfs/go-ipfs/issues/6383. Basically, the gateway has trouble finding content.

Closing as this is a bug, not a documentation issue.

**Closed by Stebalien** 2019-07-29 23:45 UTC
Labels: design-content, docs-ipfs
